# Generated by Django 3.1.2 on 2021-01-24 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210124_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='users',
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='review.category'),
        ),
        migrations.AlterField(
            model_name='business',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
