# Generated by Django 3.1.2 on 2021-02-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20210224_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='images',
        ),
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
