# Generated by Django 3.1.2 on 2021-03-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20210226_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
